name: 'metricmind'
version: '1.0.0'
config-version: 2

profile: 'metricmind'

model-paths: ["models"]
seed-paths: ["../mock_data"]

models:
  metricmind:
    staging:
      +materialized: view
    transformed:
      +materialized: table
